services:
  webserver:
    image: php:8.3-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    build:
      context: .
      dockerfile: apache/Dockerfile
    env_file:
      - .env
    expose:
      - 9000

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command: --lower_case_table_names=0
    ports:
      - "3306:3306"
    volumes:
      - ./sql/create.sql:/docker-entrypoint-initdb.d/create.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}