version: '3'
services:
  webserver:
    image: php:8.2-cli
    ports:
      - "80:80"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "composer install; php -S 0.0.0.0:80 -t public"

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mupin
    ports:
      - "3306:3306"
    volumes:
      - ./sql/create_mupin.sql:/docker-entrypoint-initdb.d/create_mupin.sql
      - ./my.cnf:/etc/mysql/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mupin